version: "3.9"

services:
  db:
    container_name: my-db-container
    image: postgres:latest
    environment:
      - POSTGRES_USER=numbers_user
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=numbers_db
      - POSTGRES_INITDB_ARGS="-A md5"
    ports:
      - "54321:5432"
    restart: always