version: "3.9"

services:
  db:
    container_name: my-db-container
    image: postgres:latest
    environment:
      - POSTGRES_USER=numbers_user
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=numbers_db
      - POSTGRES_INITDB_ARGS="-A md5"
    ports:
      - "54321:5432"
    restart: always

  bot:
    container_name: my-bot-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 54321
      DB_USER: numbers_user
      DB_PASSWORD: 123123
      DB_NAME: numbers_db
    restart: always
    links:
      - db
    depends_on:
      - db