# Generated by Django 4.0.5 on 2022-06-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
